### ISSUE TITLE
Running with docker does not work.

### ISSUE THREAD

**Issue by SiggyF** [openearth/flowmap#2]
On windows I cannot get my files to be seen by the flowmap software, using the docker approach. 
I tried /d:/d but files are not showing up. Not even with `docker run -v /d:/d /bin/ls /d`. 
Can you provide some guidance on how to run it on windows (7).

**Comment by SiggyF** [comment]
Can you test the container under windows?

**Comment by avgils** [comment]
On Windows 7 you can only mount folders from /c/Users/<username>. Other folders are not mounted in the virtual box machine.

**Comment by SiggyF** [comment]
Invalid issue, see avgils comment.
