### ISSUE TITLE
Overestimation of water depths in subgrid module

### ISSUE THREAD

**Issue by TvWoerkom** [openearth/flowmap#57]
* Flowmap generator version: 1.0.2
* Python version: 3.5
* Operating System: Windows

### Description

The subgrid module does often overestimate the waterdepths after subgridding, which might be caused by the fact that the old netcdf cells are not perfectly covered by slice that masks out the new subgridded cells. Therefore the new slice has a smaller area than the original netcdf cell, and thus the corresponding water depth increases.

### What I Did
I enlarged the mask from which the DEM slice is taken, so all cells are always included.

In the build_tables function within subgrid.py, the DEM slice is enlarged by:

face_px2slice = np.s_[
            face_px[:, 1].min():face_px[:, 1].max()**+2**,
            face_px[:, 0].min():face_px[:, 0].max()**+2**
        ]

**Comment by SiggyF** [comment]
I improved the dem masking in  #58. Can you elaborate on the  `+2`?

**Comment by SiggyF** [comment]
Assuming this was fixed in #58
